---
# Install basic tower to run on the required servers
- hosts: towers
  name: Install a basic tower instance ready for configuration
  roles:
    - tower_install_application
    - tower_configure_application
